<!DOCTYPE html>
<html lang="en">

<title>PS70: Intro to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../style.css" rel="stylesheet">


<nav class="navbar navbar-expand-sm navbar-dark" style=" color: #EEE7E8;">
<div class="container-fluid">
      <div class="flexrow">
      <h2 class="nav-title">PS70 - Xander Patton</h2>
    </div>
    <div class="navbar-nav">
      <h4><a class="nav-link" href="../index.html">Home</a></h4>
      <h4><a class="nav-link" href="../about.html">About</a></h4>
    </div>
  </div>
</nav>

<body>
<xmp style="display:none;">
<div class="textcontainer">
<p class="margin">   </p>

<h3>Week 2: 2D Design & Cutting</h3>
<p class = "margin"></p>
<p class = "margin"></p>

<h4>Assignment 1: The Box</h4>
<p class = "margin"></p>
<p> For this assignment, I threw practicality out of the window, instead wanting to play with other geometric shapes.
  I figured, if pyramids are one of the most stable structures because of their triangular form, then that would be a shape
  that would serve me well. After printing, the box fit together perfectly well, but unfortunately needed a little bit of
  extra support to stay together (hot glue).
</p>
<p class = "margin"></p>
<img width="640" height="640" src="./CompleteBox.JPG">
<p class = "margin"></p>
<img width="640" height="640" src="./FusionBox.png">
<p class = "margin"></p>
<p class = "margin"></p>

<h4>Assignment 2: Tutorials</h4>
<p class = "margin"></p>
<P> For assignment 2, I decided that it would be a good idea to stay on theme with my final project and follow a tutorial
  for how to make a flower pot. 
</P>
<p class = "margin"></p>
<img width="640" height="640" src="./Flower Pot.png">
<p class = "margin"></p>
Used a YouTube video by Evan Schwartz: <a href="https://www.youtube.com/watch?v=DOpz7_PcwJE">Fusion360 Plant Pot</a>
<p class = "margin"></p>

<h4>Assignment 3: Fusion Modeling</h4>
<p class = "margin"></p>
<p> My first goal was to recreate a rubber mallet found in the shop. I measured its head to have a diameter of 63mm in the center and 55mm at its ends. I measured the handle to have a width of 24.5mm at the head, and 33mm at the base. For the height of the handle, I measured it to be 19mm.</p>
<p class = "margin"></p>
<img width="640" height="640" src="./Mallet.JPG">
<p class = "margin"></p>
<img width="640" height="640" src="./Mallet.png">
<p class = "margin"></p>
<p> My next object goal was to create a model of an empty wire spool. For this, I measured the spool to be 57mm across in length, with the larger ends each being 2mm thick. I found each of the ends to have a diameter of 55mm, with the hole cutout of them being 20mm in diameter. The middle cylinder (the connection point) had a diameter of 27mm. </p>
<p class = "margin"></p>
<img width="640" height="640" src="./SolderSpool.JPG">
<p class = "margin"></p>
<img width="640" height="640" src="./WireSpool.png">
<p class = "margin"></p>



</div>
</xmp>
</body>

<script src="../strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>